apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
    - name: app
      image: busybox
      args:
        - /bin/sh
        - -c
        - 'while true; do touch /tmp/heartbeat.txt; sleep 5; done;'
      livenessProbe: # The probe will periodically check the modification timestamp is older than 1 minute, if
        # yes, kubernetes assume the application is not functioning as expected and restarts the container.
        exec:
          command:
            - test `find /tmp/heartbeat.txt --mmin -1` # Find the file less than 1 minute old
        initialDelaySeconds: 5
        periodSeconds: 30
