apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # read/write access by a single node
  hostPath:
    path: /data/db# # mounts the directory from the host node's filesystem

