apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs-vol
    - name: sidecar
      image: busybox
      command: [ "sh", "c", "while true; do if [ \"$(cat /var/log.nginx/error.log | grep 'error')\" != \"\" ]; then echo 'Error discoverrd!]; fi;\
        sleep 10; done" ]
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs-vol
  volumes:
    - name: logs-vol
      emptyDir: { }