apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
spec:
  containers:
    - name: http-server
      image: httpd:2.4.46
      startupProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 15
