apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-awesome-quota
spec:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 1024m
    limits.cpu: "4"
    limits.memory: 4096m

# controlplane $ kubectl describe resourcequota team-awesome-quota --namespace=team-awesome
# Name:            team-awesome-quota
# Namespace:       team-awesome
# Resource         Used  Hard
# --------         ----  ----
# limits.cpu       0     4
# limits.memory    0     4096m
# pods             0     2
# requests.cpu     0     1
# requests.memory  0     1024m
# controlplane $